### ISSUE TITLE
Reuters News Source not working

### ISSUE THREAD

**Issue by fholzknecht** [mannau/tm.plugin.webmining#10]
Entity 'ldquo' not defined
Entity 'rdquo' not defined
Opening and ending tag mismatch: div line 60 and body
Opening and ending tag mismatch: body line 59 and html
Premature end of data in tag html line 1
Fehler: 1: Entity 'ldquo' not defined
2: Entity 'rdquo' not defined
3: Opening and ending tag mismatch: div line 60 and body
4: Opening and ending tag mismatch: body line 59 and html
5: Premature end of data in tag html line 1

**Comment by mannau** [comment]
Sorry - just tried and worked for me.
Will re-open the Issue if you can give me a 
1. Reproducible example/code snippet
2. The `sessionInfo()` output
