### ISSUE TITLE
Failed to load External Entity GoogleNewsSource

### ISSUE THREAD

**Issue by DFJL** [mannau/tm.plugin.webmining#14]
Hi Mannau.Thank you for this amazing package.I develope an aplication of web scrapping and text analyitics based on this package, with the Google News API, but now I want to put it in production I get the following error:

```
#Query
  elementsOtros<-c("george orwell","bob marley","barack obama","christopher nolan","jose mujica","lionel messi","hadley wickham","john chambers")

elements<-c(elementsLAFT,elementsOtros)

evaluate<-as.vector(as.matrix(elements))

TevLAFT<- WebCorpus(GoogleNewsSource(evaluate))

Error 1: Unknown IO error2: failed to load external entity "http://news.google.com/news?hl=en&q=lionel%20messi&ie=utf-8&num=100&output=rss
```

**Comment by DFJL** [comment]
Thank you very much Mario.

**Comment by ctorrez** [comment]
Hi Mannu. Thank you for you package, I am trying to use your package in my research project, but I get the following error:
`googlenews <- WebCorpus(GoogleNewsSource("Microsoft"))`

> Unknown IO errorfailed to load external entity "http://news.google.com/news?hl=en&q=Microsoft&ie=utf-8&num=100&output=rss"

> Error: 1: Unknown IO error2: failed to load external entity "http://news.google.com/news?hl=en&q=Microsoft&ie=utf-8&num=100&output=rss"

Thanks,

**Comment by ddten** [comment]
How do you then check all the news as being positive or negative?

**Comment by keshav-rathi** [comment]
Hi Mannau. I am still getting the same error when using Google news and Yahoo Finance.

> googlenews <- WebCorpus(GoogleNewsSource("Microsoft"))
Unknown IO errorfailed to load external entity "http://news.google.com/news?hl=en&q=Microsoft&ie=utf-8&num=100&output=rss"
Error: 1: Unknown IO error2: failed to load external entity "http://news.google.com/news?hl=en&q=Microsoft&ie=utf-8&num=100&output=rss"

> yahoofinance <- WebCorpus(YahooFinanceSource("MSFT"))
Unknown IO errorfailed to load external entity "http://feeds.finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US"
Error: 1: Unknown IO error2: failed to load external entity "http://feeds.finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US"

**Comment by keshav-rathi** [comment]
Hi Mannau. I am still getting the same issue when using GoogleNews and YahooFinance.

> googlenews <- WebCorpus(GoogleNewsSource("Microsoft"))
Unknown IO errorfailed to load external entity "http://news.google.com/news?hl=en&q=Microsoft&ie=utf-8&num=100&output=rss"
Error: 1: Unknown IO error2: failed to load external entity "http://news.google.com/news?hl=en&q=Microsoft&ie=utf-8&num=100&output=rss"

> yahoofinance <- WebCorpus(YahooFinanceSource("MSFT"))
Unknown IO errorfailed to load external entity "http://feeds.finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US"
Error: 1: Unknown IO error2: failed to load external entity "http://feeds.finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US"

Please help
