### ISSUE TITLE
Parameters for latest news or news from last n days?

### ISSUE THREAD

**Issue by potholiday** [mannau/tm.plugin.webmining#16]
I have installed this package from CRAN (tm.plugin.webmining_1.3 tm_0.6-2) and my R version is 3.3.1 . I want to get latest news or news from last n days?

lastndays=2
`WebCorpus(GoogleFinanceSource("NASDAQ:MSFT",params = list(hl = "en", q = query, ie = "utf-8",  start = 0, num = 20, output = "rss",lastndays=2)))`

also some of the functions are not working `WebCorpus(GoogleNewsSource("Microsoft")), WebCorpus(YahooFinanceSource("MSFT"))` returns similar error

```
Unknown IO errorfailed to load external entity "http://feeds.finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US"
Error: 1: Unknown IO error2: failed to load external entity "http://feeds.finance.yahoo.com/rss/2.0/headline?s=MSFT&region=US&lang=en-US"
```

**Comment by mannau** [comment]
`lastndays` is AFAIK no valid parameter for Google Finance feeds. 

The call

```python
WebCorpus(GoogleNewsSource("Microsoft"))
```
works on my computer. Unfortunately
```python
WebCorpus(YahooFinanceSource("MSFT"))
```
does not. Will be fixed soon.

Best,
mario

**Comment by biranchi2018** [comment]
is it fixed yet ?
