### ISSUE TITLE
Filter by language in GoogleNews

### ISSUE THREAD

**Issue by DFJL** [mannau/tm.plugin.webmining#17]
Hi Mario,

I am trying to specify the language with hl="es" because the api is biased to the english language.But when I put that parameter, the api just ignored.

Do you know how I can change the language?

Thank you

**Comment by mannau** [comment]
unfortunately - no. It also seems that google news has closed - in spain at least:
https://support.google.com/news/answer/6140047?hl=es
best,
mario
