### ISSUE TITLE
No such file or directory failed to load external entity

### ISSUE THREAD

**Issue by parisairam** [mannau/tm.plugin.webmining#18]
Hi Mannau,

When I try to run the below code , I am getting the follow error:

**Code:**
`a<-WebCorpus(GoogleNewsSource("Demonetization"))`

**Error:**
```
No such file or directoryfailed to load external entity "http://news.google.com/news?hl=en&q=Demonetization&ie=utf-8&num=100&output=rss"

Error: 1: No such file or directory
2: failed to load external entity "http://news.google.com/news?hl=en&q=Demonetization&ie=utf-8&num=100&output=rss"
```

**Comment by phrieder** [comment]
Hi Mannau,

Thanks so much for the great package. I experienced the same error message as parisairam, wondered if you had any thoughts around that?

**Comment by mannau** [comment]
code works for me - you could check your internet connection.
best,
m
