### ISSUE TITLE
YahooNews RSS feed returns no data

### ISSUE THREAD

**Issue by mannau** [mannau/tm.plugin.webmining#7]
as reported by Eliano:
There seems to be an issue with the function YahooNewsSource.
WebCorpus(YahooNewsSource("microsoft"))
StartTag: invalid element name
Extra content at the end of the document
Error: 1: StartTag: invalid element name
2: Extra content at the end of the document

**Comment by mannau** [comment]
Fixed now (use html instead)

**Comment by ElianoMarques** [comment]
Thanks

**Comment by ElianoMarques** [comment]
Just tried to install again from github and seems to be an error. 

Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/emarques/Documents/R/R-3.1.1/library/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

I have rJava installed so not sure if there's something on the code? 

Eliano

**Comment by mannau** [comment]
thats a tricky one - there seems to be a problem for install_github for
multiarch.
Try the following command:
> install_github("mannau/tm.plugin.webmining", args = "--no-multiarch")
best,
mario


Am 10/05/15 um 21:42 schrieb ElianoMarques:

**Comment by ElianoMarques** [comment]
That solved the issue of installing from github but apparently the function still returns an error. 

WebCorpus(YahooNewsSource("Microsoft"))
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by mannau** [comment]
windows issue which is fixed now - just re-install newest version from
github.
best,
m

Am 10/05/15 um 22:33 schrieb ElianoMarques:
