### ISSUE TITLE
Adding the query to the metadata

### ISSUE THREAD

**Issue by DFJL** [mannau/tm.plugin.webmining#8]
Hi Mario.Thank you for this great package!!.

Im developing an application of text analytics with you package and in the final stage i need to add the query element to the metadata of the webcorpuses created.

For example:

the query is 

```
query<-c("bob marley","bob dylan","john lennon")
corpus<-WebCorpus(GoogleNewsSource(query))
```
For every document in corpus, I need an identifyer of the query origin of the document.

There is a easy way to obtain this data?

Thank you very much!!

**Comment by mannau** [comment]
Hi Felipe,
the query information is stored in the resulting `corpus` object:
```
corpus$meta$source$feedurls
> corpus$meta$sourcefeedurls
[1] "http://news.google.com/news?hl=en&q=bob%20marley&ie=utf-8&num=30&output=rss" 
[2] "http://news.google.com/news?hl=en&q=bob%20dylan&ie=utf-8&num=30&output=rss"  
[3] "http://news.google.com/news?hl=en&q=john%20lennon&ie=utf-8&num=30&output=rss"
```
However, the queries are not directly assigned to each document. It can be assumed that documents are retrieved in `$feedurls` order (e.g. first 30 to `bob marley`, next 30 to `bob dylan`, last 30 to `john lennon`.)

If you need more direct control I'd suggest to split the query in 3 corpora, assign the query to each document and join the corpora afterwards:
```
corpus1 <- WebCorpus(GoogleNewsSource("bob marley"))
corpus2 <- WebCorpus(GoogleNewsSource("bob dylan"))
corpus3 <- WebCorpus(GoogleNewsSource("john lennon"))

corpus1 <- lapply(corpus1, function(x) {meta(x, "feedurl") <- corpus1$meta$source$feedurls; x})
corpus2 <- lapply(corpus2, function(x) {meta(x, "feedurl") <- corpus2$meta$source$feedurls; x})
corpus3 <- lapply(corpus3, function(x) {meta(x, "feedurl") <- corpus3$meta$source$feedurls; x})
corpusall <- c(corpus1, corpus2, corpus3)
```
You can retrieve the feedurl of each document using
```
sapply(corpusall, function(x) meta(x, "feedurl"))
```
Hope that helps!
